services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sneakershop-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
    name: sneakershop-mssql-data